### ISSUE TITLE
Рушится дизайнер

### ISSUE THREAD

**Issue by kosozhihin** [yandexmobile/yandexmapkit-wp#8]
В проекте, использующем MapKit, при открытии XAML падает дизайнер со следующей ошибкой (число варьируется):

```
System.Runtime.Remoting.RemotingException
[8796] Designer process terminated unexpectedly!
```

Изредка вместо неё показывается следующее:

```
Microsoft.Expression.DesignHost.Isolation.Remoting.RemoteException
Could not load file or assembly 'LocationService.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=24eec0d8c86cda1e' or one of its dependencies. The system cannot find the file specified.
   at System.Device.Location.GeoCoordinateWatcher.Dispose(Boolean disposing)
   at System.Device.Location.GeoCoordinateWatcher.Finalize()
```

Очень напоминает [проблему этих товарищей](http://mvvmlight.codeplex.com/discussions/428701).

**Comment by solareye** [comment]
Очень странно! С новой версией дизайнер работает очень хорошо.

**Comment by a-klimashevsky** [comment]
Таже самая ошибка, мапкит с нугета

**Comment by ghost** [comment]
Здравствуйте!
При проблемах с дизайнером разметку можно создать вручную путем копирования кода из примера. Отдельные участки XAML можно временно закомментировать, чтобы восстановить работу дизайнера.

**Comment by solareye** [comment]
Да, можно закомментировать то, что касается непосредственно карты, но, повторюсь, с новой версией мапкита (при удаление старой и "пересбор" проекта) заработало-таки без падений.

**Comment by kosozhihin** [comment]
Это костыль, который проблему окончательно не решает.
К тому же, падает дизайнер на всех формах в проекте, а не только на тех, где есть карта. Дизайнер начинает работать только если вычистить карты из проекта и удалить референсы.

Я мапкит начал с января использовать, пользовался только самой свежей версией.
